### ISSUE TITLE
Images Showing Up With Red Cross

### ISSUE THREAD

**Issue by Dinamiko** [Dinamiko/dk-pdf#11]
https://wordpress.org/support/topic/images-showing-up-with-red-cross

01 show image errors
in .../plugins/dk-pdf/includes/mpdf60/config.php in line 132 change this:
$this->showImageErrors = false;
for this:
$this->showImageErrors = true;

...

**Comment by Dinamiko** [comment]
see related tickets and responses:
https://wordpress.org/support/plugin/dk-pdf

**Comment by tnchuntic** [comment]
I've encountered this issue also and found out that its cause by unveil lazy load plugin. I am still testing on how to unhook the lazy load if on pdf creation.
