### ISSUE TITLE
Add Proper Internationalization

### ISSUE THREAD

**Issue by renatonascalves** [Dinamiko/dk-pdf#29]
Currently, it's not properly internationalized: https://translate.wordpress.org/projects/wp-plugins/dk-pdf

Some more info of how to do that: https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

**Comment by Dinamiko** [comment]
Temporary closing this issue due to plugin refactoring plan. Once I have next steps decided I may come back to this issue and reopen it or create a new one based on it.
