### ISSUE TITLE
add compatibility to other plugins like visual composer...

### ISSUE THREAD

**Issue by Dinamiko** [Dinamiko/dk-pdf#37]

**Comment by contemplate** [comment]
Hi @Dinamiko this should work:
https://wordpress.org/support/topic/dk-pdf-and-wpbakery-visual-composer-version-4-12-1/#post-9408595

**Comment by Dinamiko** [comment]
Temporary closing this issue due to plugin refactoring plan. Once I have next steps decided I may come back to this issue and reopen it or create a new one based on it.
