### ISSUE TITLE
Show content only on PDF -> add [dkpdf-add] shortcode

### ISSUE THREAD

**Issue by alexanderhofstaetter** [Dinamiko/dk-pdf#41]
Here my shortcode funtion, maybe you want to integrate it.

/**
* [dkpdf-add]content to add[/dkpdf-add]
* This shortcode is used to add pieces of content in the generated PDF
* @return string
*/
function dkpdf_add_shortcode( $atts, $content = null ) {
	$atts = shortcode_atts( array(), $atts );
	$pdf = get_query_var( 'pdf' );
	
	if( $pdf )
		return do_shortcode( $content );
	
	return '';
}
add_shortcode( 'dkpdf-add', 'dkpdf_add_shortcode' );

**Comment by Dinamiko** [comment]
Hi alexanderhofstaetter,

looks great, I'm going check it out soon, once I have more info I let you know, 

thanks again 👍

**Comment by Dinamiko** [comment]
Temporary closing this issue due to plugin refactoring plan. Once I have next steps decided I may come back to this issue and reopen it or create a new one based on it.
