### ISSUE TITLE
lots of warnings in debug mode

### ISSUE THREAD

**Issue by alexanderhofstaetter** [Dinamiko/dk-pdf#48]
Hi!

when i enabled the WP Debug Mode i get lots of warnings when i try to generate a pdf:

I visit https://domain.com/page-slug-name/?pdf=1234

and i get the following warnings:

`
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mPDF has a deprecated constructor in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 89

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; grad has a deprecated constructor in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/grad.php on line 3

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mpdfform has a deprecated constructor in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/mpdfform.php on line 3

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; cssmgr has a deprecated constructor in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 3

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; SVG has a deprecated constructor in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/svg.php on line 33

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; otl has a deprecated constructor in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/otl.php on line 12

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: A non-numeric value encountered in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 31965

Warning: A non-numeric value encountered in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 31965

Warning: A non-numeric value encountered in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 31965

Warning: A non-numeric value encountered in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 31965

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: A non-numeric value encountered in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 31965

Warning: A non-numeric value encountered in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 31965

Warning: A non-numeric value encountered in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 31965

Warning: A non-numeric value encountered in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 31965

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139

Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/otl.php:12) in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 8297

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/otl.php:12) in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 1706
mPDF error: Some data has already been output to browser, can't send PDF file`

When i disable WP Debug mode I can download my PDF and the content is OK.

**Comment by alexanderhofstaetter** [comment]
i can find them in my serverlogs also, they are spamming into my logs everytime a PDF gets generated ...

22176#0: *28602 FastCGI sent in stderr: "ses/cssmgr.php on line 1139
PHP message: PHP Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139
PHP message: PHP Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190
PHP message: PHP Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190
PHP message: PHP Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136
PHP message: PHP Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1136
PHP message: PHP Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139
PHP message: PHP Warning: Cannot assign an empty string to a string offset in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1139
PHP message: PHP Warning: Illegal string offset 'ID' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190
PHP message: PHP Warning: Illegal string offset 'LANG' in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/classes/cssmgr.php on line 1190
PHP message: PHP Warning: A non-numeric value encountered in /var/www/vhosts/domain.com/wp-content/plugins/dk-pdf/includes/mpdf60/mpdf.php on line 31965
PH

**Comment by Dinamiko** [comment]
Hi alexanderhofstaetter,

Which versions are your using?

* Server:
* PHP: 
* WordPress: 
* DK PDF:

A quick tip for getting all the above info is using Query Monitor plugin and see the Environtment info via the admin bar.

Thanks,
Emili

**Comment by alexanderhofstaetter** [comment]
Server: CentOs 7, nginx 1.11.10
PHP: 7.1.6
Wordpress 4.8
DK PDF: 1.9

**Comment by Dinamiko** [comment]
More warnings from wp.org
https://wordpress.org/support/topic/php-warning-135/
https://wordpress.org/support/topic/warnings-in-debug-log-for-newest-version/

**Comment by Dinamiko** [comment]
e36e22b13f801a43b00573524503adca065b92c8
