### ISSUE TITLE
Improve CSS

### ISSUE THREAD

**Issue by Dinamiko** [Dinamiko/dk-pdf#5]
Users wants to adjusts the CSS of the generated PDF, like changing the color of links...

**Comment by LunkSnee** [comment]
This is already available by adding css into the dkpdf-index.php. I don't know to add this into the administrative panel, but it would be very possible to have the admin panel include a css box, which is then loaded into the dkpdf-index.php.

**Comment by Dinamiko** [comment]
https://github.com/Dinamiko/dk-pdf/commit/0833b708a755be5976537b19d5aef45b1f47eb2c
https://github.com/Dinamiko/dk-pdf/commit/f4b583a2af1db8452c79852f11274131c4b5d2dc

**Comment by Dinamiko** [comment]
Added in 1.5
