### ISSUE TITLE
Bookmark link should be created too

### ISSUE THREAD

**Issue by ghost** [Dinamiko/dk-pdf#57]
I have a page with a summary at the beginning with bookmark link pointing to sections within the page. When I create a pdf, it doesn’t switch the bookmark link to point to the according section inside the pdf but let them as they are and point to the website.

It would be great if the plugin would switch them automatically to link inside the pdf.

**Comment by Dinamiko** [comment]
Hi Dostoi, 

OK I´m taking note of this functionality, let see if it can be added in a future version, thanks.
