### ISSUE TITLE
Latest update broke font awesome support

### ISSUE THREAD

**Issue by talamihg** [Dinamiko/dk-pdf#62]
After installing v1.9.6 that takes advantage of mPDF v7, symbols created with the fa cheat sheet codes no longer work. Do I need to do something special? Like include font awesome .tff file as described here? http://wp.dinamiko.com/demos/dkpdf/doc/how-to-add-custom-fonts/

**Comment by talamihg** [comment]
Tested - that is just the case and issue. You must create a new font folder and upload a .ttf or .woff file of fontawesome and add it in with filters. In your documentation on http://wp.dinamiko.com/demos/dkpdf/doc/fontawesome-icons-support/  you should mention that you first need to add custom font support with the 2 filters.

**Comment by Dinamiko** [comment]
@talamihg OK I´ll add it to the docs, thanks.
