### ISSUE TITLE
CSS Classes and ID's?

### ISSUE THREAD

**Issue by matchlessweb** [Dinamiko/dk-pdf#72]
I don't see any information in the documentation regarding css classes and ID's. I'd like to customize the look of my PDFs but I don't believe I can even start without knowing the appropriate selectors. Am I missing something?

**Comment by Dinamiko** [comment]
Hi @matchlessweb,

You can use your own classes and IDs in the template, here you have more info about how to do a template customization: http://wp.dinamiko.com/demos/dkpdf/doc/how-to-use-dk-pdf-templates-in-your-theme/

Regarding which CSS currently supported in mPDF library (the library used to generate the PDF): https://mpdf.github.io/css-stylesheets/supported-css.html

Thanks,
Emili
